Model pACE_B8_N4_18_07_lap_dia_1.2, Test bulk_Si_bc8
Test run at 2020-09-18 14:37

model file: /Users/Cas/gits/testing-framework/example_models/Si/run_dir/../models/pACE_B8_N4_18_07_lap_dia_1.2/model.py
============================================================
import os
from ase.calculators.lammpsrun import LAMMPS

os.environ["ASE_LAMMPSRUN_COMMAND"]="/Users/Cas/gits/lammps-ace/src/lmp_serial"

model_dir = os.path.dirname(os.path.realpath(__file__))

parameters = {'pair_style': 'pace',
              'pair_coeff': ['* * Si_B8_N4_18_07_lap_dia_1.2_rep_2B+ACE.ace Si']}

files = [os.path.join(model_dir, "Si_B8_N4_18_07_lap_dia_1.2_rep_2B+ACE.ace")]

calculator = LAMMPS(parameters=parameters, files=files)

name="ACE"

no_checkpoint = True
============================================================
test file: /Users/Cas/gits/testing-framework/scripts/../tests/Si/bulk_Si_bc8/test.py
============================================================
import os.path, lattice

properties = lattice.do_lattice(os.path.abspath(os.path.dirname(__file__)), 'cubic')
============================================================
/Users/Cas/miniconda3/lib/python3.8/site-packages/ase-3.20.0b1-py3.8.egg/ase/calculators/lammpsrun.py:191: UserWarning: You are using an old syntax to set 'parameters'.
Please use LAMMPSRUN.set().
  warnings.warn(self.legacy_warn_string.format("parameters"))
relax bulk
relax_config failed to read base run config from  Si-model-None-test-bulk_Si_bc8-bulk-relaxed.xyz
relax_config symmetry before refinement at default tol 1.0e-6
ase.spacegroup.symmetrize: prec 1e-06 got symmetry group number 206 , international (Hermann-Mauguin) Ia-3 , Hall  -I 2b 2c 3
relax_config symmetry after refinement
ase.spacegroup.symmetrize: prec 0.01 got symmetry group number 206 , international (Hermann-Mauguin) Ia-3 , Hall  -I 2b 2c 3
relax_config trying to maintain symmetry
/Users/Cas/miniconda3/lib/python3.8/site-packages/ase-3.20.0b1-py3.8.egg/ase/optimize/precon/lbfgs.py:132: UserWarning: The system is likely too small to benefit from the standard preconditioner, hence it is disabled. To re-enable preconditioning, call`PreconLBFGS` by explicitly providing the kwarg `precon`
  warnings.warn('The system is likely too small to benefit from ' +
PreconLBFGS:   0  14:37:22    -1303.748321       0.7597       0.0591
PreconLBFGS:   1  14:37:22    -1304.105260       0.0214       0.0162
PreconLBFGS:   2  14:37:22    -1304.139859       0.0695       0.0008
PreconLBFGS:   3  14:37:22    -1304.140689       0.0206       0.0011
PreconLBFGS:   4  14:37:23    -1301.271042       0.3912       0.0056
PreconLBFGS:   5  14:37:24    -1301.271133       0.3997       0.0047
PreconLBFGS:   6  14:37:24    -1301.271133       0.3988       0.0048
Traceback (most recent call last):
  File "/Users/Cas/gits/testing-framework/scripts/run-model-test.py", line 129, in <module>
    import test  # import and run the current test
  File "/Users/Cas/gits/testing-framework/scripts/../tests/Si/bulk_Si_bc8/test.py", line 3, in <module>
    properties = lattice.do_lattice(os.path.abspath(os.path.dirname(__file__)), 'cubic')
  File "/Users/Cas/gits/testing-framework/scripts/../share/lattice.py", line 89, in do_lattice
    bulk = relax_config(bulk, relax_pos=True, relax_cell=True, tol=tol, traj_file="lattice_bulk_traj.xyz", method=method,
  File "/Users/Cas/gits/testing-framework/scripts/../share/utilities.py", line 207, in relax_config
    opt.run(tol, max_steps)
  File "/Users/Cas/miniconda3/lib/python3.8/site-packages/ase-3.20.0b1-py3.8.egg/ase/optimize/precon/lbfgs.py", line 375, in run
    return Optimizer.run(self, fmax, steps)
  File "/Users/Cas/miniconda3/lib/python3.8/site-packages/ase-3.20.0b1-py3.8.egg/ase/optimize/optimize.py", line 275, in run
    return Dynamics.run(self)
  File "/Users/Cas/miniconda3/lib/python3.8/site-packages/ase-3.20.0b1-py3.8.egg/ase/optimize/optimize.py", line 162, in run
    for converged in Dynamics.irun(self):
  File "/Users/Cas/miniconda3/lib/python3.8/site-packages/ase-3.20.0b1-py3.8.egg/ase/optimize/optimize.py", line 141, in irun
    self.step()
  File "/Users/Cas/miniconda3/lib/python3.8/site-packages/ase-3.20.0b1-py3.8.egg/ase/optimize/precon/lbfgs.py", line 256, in step
    self.line_search(r, g, e, previously_reset_hessian)
  File "/Users/Cas/miniconda3/lib/python3.8/site-packages/ase-3.20.0b1-py3.8.egg/ase/optimize/precon/lbfgs.py", line 369, in line_search
    raise RuntimeError('Wolff lineSearch failed!')
RuntimeError: Wolff lineSearch failed!
