Model V, Test bulk_V_bcc
Test run at 2020-08-31 18:50

model file: ../../models/V/model.py
============================================================
Traceback (most recent call last):
  File "../../../scripts/run-model-test.py", line 108, in <module>
    sys.stdout.write(open(model_file).read())
FileNotFoundError: [Errno 2] No such file or directory: '../../models/V/model.py'
