Model TiAl_Ti_Al_TiAlV_FLD_PH_MD_1_B12_N3_12_lap_1.1, Test bulk_TiAlV_bcc
Test run at 2020-09-09 09:11

model file: ../../models/TiAl_Ti_Al_TiAlV_FLD_PH_MD_1_B12_N3_12_lap_1.1/model.py
============================================================
import pyjulip
import os
import glob

model_dir = os.path.dirname(os.path.realpath(__file__))
pot_name = glob.glob(os.path.join(model_dir,"*.json"))[0]

calculator = pyjulip.ACE(pot_name)

no_checkpoint = True

name = "ACE"
============================================================
test file: /Users/Cas/gits/testing-framework/scripts/../tests/TiAl/bulk_TiAlV_bcc/test.py
============================================================
Traceback (most recent call last):
  File "../../../scripts/run-model-test.py", line 114, in <module>
    sys.stdout.write(open(test_file).read())
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Cas/gits/testing-framework/scripts/../tests/TiAl/bulk_TiAlV_bcc/test.py'
